Fixing Turbo C 1.01 build. Unlike TC3, TC1 doesn't have the "automatic far pointer" option so the following linker error still remains:
Turbo C++  Version 1.01 Copyright (c) 1990 Borland International
Turbo Link  Version 3.01 Copyright (c) 1987, 1990 Borland International
Error: Group DGROUP exceeds 64K